#TABLE

12

beat~
6
0
0
0
You @rbeat@n your chest like a @grampaging gorilla!~
$1 @rbeats@n $s chest @ysquealing@n with a @rmighty fury!~
You commence @rBeating@n $N about the head and shoulders.~
@yMadly squealing,@n $1 begins @rbeating@n $N about the head and shoulders.~
With an @yinsane squeal,@n $1 begins to @rBeat@n you about the head and shoulders.~
You have dream of a severe beating about the head and shoulders.~
~
~
~
~
~
~
~
~
~
~
~
~

bully~
8
0
0
0
You look around for someone smaller than you.~
$n looks for someone to push around~
Picking $N up by the neck, you rattle $S brains until you get your way.~
$n grabs $N by the neck, rattling $S head until $e gets $s way.  What a bully!~
$n grabs you by the neck and begins to rattle your brains.  Better do what $e says!~
~
You begin speaking in tongues and hitting yourself.~
$n falls to the ground in a fit and bangs $s head on the ground.~
~
~
~
~
~
~
~
~
~
~

grin~
6
0
0
0
Grinning evilly, you flash your tusks.~
Flashing $s tusks, $n grins evilly.~
Flashing your tusks, you grin evilly at $N.~
$n grins evilly at $N, flashing his tusks.~
Grinning evilly at you, $n's tusks become very apparent.~
~
~
~
~
~
~
~
~
~
~
~
~
~

grunt~
0
0
0
0
You grunt noncommittally.~
$1 grunts noncommittally.~
You grunt at $2 suspiciously.~
$1 grunts suspiciously at $2.~
$1 grunts suspiciously at you.~
~
You grunt happily to yourself.~
$n grunts happily to $mself.~
~
~
~
~
~
~
~
~
~
~

lick~
6
0
0
0
~
~
You lick $2 with your @rcoarse, wet tongue@n, absentmindedly jabbing with your tusks.~
$1 gives $2 a @rlong, wet lick@n.~
Absentmindedly poking you with $s tusks, $1 gives you a @rlong, wet lick@n.~
You feel a @rlong, wet lick@n, followed by the dull jab of tusks.~
You lick your lips in anticipation, drool running down your tusks in rivulets.~
$1 licks $s lips in anticipation, rivulets of drool running down $s tusks.~
~
~
~
~
~
~
~
~
~
~

smile~
4
0
0
0
You smile happily, showing off your fine set of tusks.~
$n smiles happily, showing off $s fine set of tusks.~
Beaming a smile at $N, you flaunt your fine set of tusks.~
$n beams a smile at $N, $s fine orcish tusks gleaming.~
$n smiles happily at you, showing off $s fine set of tusks.~
~
~
~
~
~
~
~
~
~
~
~
~
~

snarl~
0
0
0
0
Your gnash your tusks and snarl.~
$n gnashes his tusks as $e snarls.~
You snarl at $N, flashing your tusks.~
$n snarls angrily at $N, flashing $s tusks.~
$n snarls angrily at you, flashing $s tusks.~
~
You snarl at yourself.~
$n snarls at $mself.~
~
~
~
~
~
~
~
~
~
~

snort~
0
0
0
0
Your snout curls as you snort loudly.~
$n's snout curls as $e snorts loudly.~
You snort angrily at $N.~
$n snorts angrily at $N.~
$n snorts angrily at you.~
~
You absentmindedly snort to yourself.~
$n absentmindedly snorts to $mself.~
~
~
~
~
~
~
~
~
~
~

squeal~
4
0
1
1
You squeal like a pig.~
$1 squeals like a pig.~
You squeal angrily at $2.~
$1 squeals angrily at $2.~
$1 squeals angrily at you.~
A loud squeal interrupts your slumber.~
You squeal in frustration.~
$1 squeals angrily.~
~
~
~
~
~
~
~
~
~
~

think~
6
0
0
0
You slowly stroke your tusks, deep in thought.~
In deep thought, $n slowly strokes $s tusks.~
Slowly stroking your tusks, you think of $N's many problems.~
Slowly stroking $s tusks, $n thinks of $N's many problems.~
Slowly stroking his tusks, $n thinks of all your many problems.~
~
~
~
~
~
~
~
~
~
~
~
~
~

wrinkle~
6
0
0
0
Showing your disgust, you wrinkle your snout.~
Showing $s disgust, $n wrinkles his snout.~
With great disgust, you wrinkle your snout at $N.~
Showing great disgust, $n wrinkles $s snout at $N.~
Wrinkling $s snout, $n is disgusted with you.~
~
~
~
~
~
~
~
~
~
~
~
~
~

yawn~
0
0
0
0
You yawn slowly, baring your tusks.~
$1 yawns slowly, revealing a fine set of tusks.~
You yawn at $N.~
$n yawns at $N.~
$n yawns at you.~
~
You let out a big yawn.~
$n lets out a big yawn.~
~
~
~
~
~
~
~
~
~
~


