#define SKILL_CAT_WEAPON            0
#define SKILL_CAT_LANGUAGE          1
#define SKILL_CAT_PHYSICAL          2
#define SKILL_CAT_SPELL             3
#define SKILL_CAT_TRADE             4
#define SKILL_CAT_SONG              5
#define SKILL_CAT_WARD              6
#define MAX_SKILL_CAT               7

#define SKILL_NONE                 -1
#define SKILL_APPRAISE              0
#define SKILL_ASSASSINATE           1
#define SKILL_BACKSTAB              2
#define SKILL_BANDAGE               3
#define SKILL_BASH                  4
#define SKILL_BEAR_GRASP            5
#define SKILL_BERSERK               6
#define SKILL_BLIND_FIGHTING        7
#define SKILL_CAMOUFLAGE            8
#define SKILL_CAMPFIRE              9
#define SKILL_CHARGE               10
#define SKILL_CIRCLE               11
#define SKILL_CLIMB                12
#define SKILL_COUNTER_ATTACK       13
#define SKILL_COVER_TRACKS         14
#define SKILL_CRITICAL_HIT         15
#define SKILL_DEATH_STRIKE         16
#define SKILL_DEMON_SLASH          17
#define SKILL_DISARM               18
#define SKILL_DISGUISE             19
#define SKILL_DODGE                20
#define SKILL_DRAGON_STRIKE        21
#define SKILL_EAGLE_CLAW           22
#define SKILL_EYE_GOUGE            23
#define SKILL_FIFTH                24
#define SKILL_FORCENATURE          25
#define SKILL_FOURTH               26
#define SKILL_FRENZY               27
#define SKILL_GARROTE              28
#define SKILL_GUARD                29
#define SKILL_HAGGLE               30
#define SKILL_HEIST                31
#define SKILL_HIDE                 32
#define SKILL_INSPECT              33
#define SKILL_KICK                 34
#define SKILL_LAY_HANDS            35
#define SKILL_LOCUST_KICK          36
#define SKILL_MEDITATE             37
#define SKILL_MELEE                38
#define SKILL_MOUNTED_FIGHTING     39
#define SKILL_OFFHAND_ATTACK       40 
#define SKILL_OFFHAND_PARRY        41
#define SKILL_PARRY                42
#define SKILL_PEEK                 43
#define SKILL_PICK_LOCK            44
#define SKILL_POISON               45
#define SKILL_POWER_STRIKE         46
#define SKILL_PROBE                47
#define SKILL_PROTECT              48
#define SKILL_PUNCH                49
#define SKILL_REGENERATION         50
#define SKILL_RESCUE               51
#define SKILL_RIDING               52
#define SKILL_SCAN                 53
#define SKILL_SEARCHING            54
#define SKILL_SECOND               55
#define SKILL_SHADOW_DANCE         56
#define SKILL_SHIELD               57  
#define SKILL_SNEAK                58
#define SKILL_SPIN_KICK            59 
#define SKILL_STEAL                60
#define SKILL_STUN                 61
#define SKILL_SWEEP                62
#define SKILL_SWEEPING_KICK        63
#define SKILL_SWIMMING             64
#define SKILL_THIRD                65
#define SKILL_TIGER_PAW            66
#define SKILL_TRACK                67
#define SKILL_TRANCE               68
#define SKILL_TRANSFER_ENERGY      69
#define SKILL_TRIP                 70
#define SKILL_TUMBLE               71
#define SKILL_UNTRAP               72

#define LANG_PRIMAL                73
#define LANG_HUMANIC               74
#define LANG_ELVISH                75
#define LANG_GNOMISH               76
#define LANG_DWARVISH              77
#define LANG_THENNISH              78
#define LANG_ENTISH                79
#define LANG_CENTAUR               80
#define LANG_SLISP                 81
#define LANG_OGRISH                82
#define LANG_TROLLISH              83
#define LANG_ORCISH                84
#define LANG_GOBLISH               85
#define LANG_VYANIAN               86
#define MAX_LANGUAGE               87

#define SPELL_FIRST                87
#define SPELL_ACID_BLAST           87
#define SPELL_ACID_STORM           88
#define SPELL_AMNESIA              89
#define SPELL_ANIMATE_CLAY         90
#define SPELL_ANIMATE_DEAD         91
#define SPELL_ARMOR                92
#define SPELL_ASTRAL_GATE          93
#define SPELL_AUGURY               94
#define SPELL_BALM                 95
#define SPELL_BANISHMENT           96
#define SPELL_BARKSKIN             97
#define SPELL_BLESS                98
#define SPELL_BLIND                99
#define SPELL_BLINDING_LIGHT      100
#define SPELL_BLINK               101
#define SPELL_BURNING_HANDS       102
#define SPELL_CALL_LIGHTNING      103
#define SPELL_CALM                104
#define SPELL_CAUSE_CRITICAL      105
#define SPELL_CAUSE_LIGHT         106
#define SPELL_CAUSE_SERIOUS       107
#define SPELL_CHAIN_LIGHTNING     108
#define SPELL_CHILLING_TOUCH      109
#define SPELL_CONFLAGRATION       110
#define SPELL_CONFUSE             111
#define SPELL_CONJURE_ELEMENTAL   112
#define SPELL_CONSTRUCT_GOLEM     113
#define SPELL_CONTINUAL_LIGHT     114 
#define SPELL_CREATE_FEAST        115
#define SPELL_CREATE_FOOD         116
#define SPELL_CREATE_LIGHT        117
#define SPELL_CREATE_WATER        118
#define SPELL_CURE_BLINDNESS      119
#define SPELL_CURE_CRITICAL       120
#define SPELL_CURE_DISEASE        121
#define SPELL_CURE_LIGHT          122
#define SPELL_CURE_POISON         123
#define SPELL_CURE_SERIOUS        124
#define SPELL_CURSE               125
#define SPELL_DETECT_EVIL         126
#define SPELL_DETECT_GOOD         127
#define SPELL_DETECT_HIDDEN       128
#define SPELL_DETECT_INVISIBLE    129
#define SPELL_DETECT_MAGIC        130
#define SPELL_DISPLACE            131
#define SPELL_DRAIN_LIFE          132
#define SPELL_EAGLE_EYE           133
#define SPELL_FAERIE_FIRE         134
#define SPELL_FEAR                135
#define SPELL_FIND_FAMILIAR       136
#define SPELL_FIND_MOUNT          137
#define SPELL_FIRE_SHIELD         138
#define SPELL_FIREBALL            139
#define SPELL_FLAME_STRIKE        140
#define SPELL_FLOAT               141
#define SPELL_FLY                 142
#define SPELL_FREEZE              143
#define SPELL_GIFT_OF_TONGUES     144
#define SPELL_GREATER_ANIMATION   145
#define SPELL_GROUP_CRITICAL      146
#define SPELL_GROUP_SERIOUS       147
#define SPELL_HALLUCINATE         148
#define SPELL_HARM                149
#define SPELL_HASTE               150
#define SPELL_HAWKS_VIEW          151
#define SPELL_HEAL                152
#define SPELL_HOLY_WRATH          153
#define SPELL_ICE_LANCE           154
#define SPELL_ICE_STORM           155
#define SPELL_IDENTIFY            156
#define SPELL_IGNITE_WEAPON       157   
#define SPELL_INFRAVISION         158  
#define SPELL_INVISIBILITY        159
#define SPELL_INVULNERABILITY     160
#define SPELL_ION_SHIELD          161
#define SPELL_LESSER_SUMMONING    162
#define SPELL_LIGHTNING_BOLT      163
#define SPELL_LOCUST_SWARM        164
#define SPELL_MAELSTROM           165
#define SPELL_MAGIC_MAPPING       166
#define SPELL_MAGIC_MISSILE       167
#define SPELL_MAJOR_ENCHANTMENT   168
#define SPELL_METEOR_SWARM        169
#define SPELL_MIND_BLADE          170
#define SPELL_MINOR_ENCHANTMENT   171
#define SPELL_MISTS_SLEEP         172
#define SPELL_MYSTIC_SHIELD       173
#define SPELL_NEUTRALIZE          174
#define SPELL_OBSCURE             175
#define SPELL_OGRE_STRENGTH       176
#define SPELL_PASS_DOOR           177
#define SPELL_POISON_CLOUD        178  
#define SPELL_POLYMORPH           179
#define SPELL_POULTICE            180
#define SPELL_PRISMIC_MISSILE     181
#define SPELL_PROTECT_EVIL        182
#define SPELL_PROTECT_GOOD        183
#define SPELL_PROTECT_LIFE        184
#define SPELL_PROT_PLANTS         185
#define SPELL_PURIFY              186
#define SPELL_RECALL              187
#define SPELL_REMOVE_CURSE        188
#define SPELL_REPLICATE           189
#define SPELL_REQUEST_ALLY        190
#define SPELL_RESIST_ACID         191
#define SPELL_RESIST_COLD         192
#define SPELL_RESIST_FIRE         193
#define SPELL_RESIST_SHOCK        194
#define SPELL_RESTORATION         195
#define SPELL_RESURRECT           196
#define SPELL_REVITALIZE          197
#define SPELL_SANCTIFY            198
#define SPELL_SCRY                199
#define SPELL_SENSE_DANGER        200
#define SPELL_SENSE_LIFE          201
#define SPELL_SHOCK               202
#define SPELL_SILENCE             203
#define SPELL_SLAY                204
#define SPELL_SLEEP               205 
#define SPELL_SLOW                206
#define SPELL_SUMMON              207
#define SPELL_SURCEASE            208
#define SPELL_TAME                219
#define SPELL_THORN_SHIELD        210
#define SPELL_TRANSFER            211
#define SPELL_TRUE_SIGHT          212
#define SPELL_TURN_UNDEAD         213
#define SPELL_VITALITY            214
#define SPELL_WATER_BREATHING     215
#define SPELL_WEB                 116
#define SPELL_WITHER              217
#define SPELL_WIZARD_LOCK         218
#define SPELL_YOUTH               219

#define TRADE_FIRST               220
#define TRADE_COOKING             220
#define TRADE_LEATHERING          221
#define TRADE_METALURGY           222
#define TRADE_WOODWORKING         223
#define MAX_TRADE                 224

#define WEAPON_FIRST              224
#define WEAPON_UNARMED            224
#define WEAPON_DAGGER             225
#define WEAPON_SWORD              226
#define WEAPON_CLUB               227
#define WEAPON_STAFF              228
#define WEAPON_POLEARM            229
#define WEAPON_MACE               230
#define WEAPON_WHIP               231
#define WEAPON_AXE                232
#define WEAPON_BOW                233
#define WEAPON_SPEAR              234

#define MAX_SKILL                 235


extern trainer_data*  trainer_list;

extern const char* skill_cat_name [ MAX_SKILL_CAT ];


/*
 *   LANGUAGES
 */


extern int        max_language;
extern flag_data  lang_flags;


int get_language  ( char_data*, int );
